export const PolicyRegistryAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_cUSD', type: 'address' },
      { name: '_premiumPool', type: 'address' },
      { name: '_owner', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'registerPolicy',
    inputs: [
      { name: 'lat', type: 'int256' },
      { name: 'lng', type: 'int256' },
      { name: 'coverageType', type: 'uint8' },
      { name: 'coverageAmount', type: 'uint256' },
      { name: 'endDate', type: 'uint40' },
    ],
    outputs: [{ name: 'policyId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'markClaimed',
    inputs: [{ name: 'policyId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'expirePolicy',
    inputs: [{ name: 'policyId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAuthorizedAgent',
    inputs: [{ name: '_agent', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getPolicy',
    inputs: [{ name: 'policyId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'policyId', type: 'bytes32' },
          { name: 'farmer', type: 'address' },
          { name: 'lat', type: 'int256' },
          { name: 'lng', type: 'int256' },
          { name: 'coverageType', type: 'uint8' },
          { name: 'coverageAmount', type: 'uint256' },
          { name: 'premiumPaid', type: 'uint256' },
          { name: 'startDate', type: 'uint40' },
          { name: 'endDate', type: 'uint40' },
          { name: 'status', type: 'uint8' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFarmerPolicies',
    inputs: [{ name: 'farmer', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'calculatePremium',
    inputs: [{ name: 'coverageAmount', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'policies',
    inputs: [{ name: 'policyId', type: 'bytes32' }],
    outputs: [
      { name: 'policyId', type: 'bytes32' },
      { name: 'farmer', type: 'address' },
      { name: 'lat', type: 'int256' },
      { name: 'lng', type: 'int256' },
      { name: 'coverageType', type: 'uint8' },
      { name: 'coverageAmount', type: 'uint256' },
      { name: 'premiumPaid', type: 'uint256' },
      { name: 'startDate', type: 'uint40' },
      { name: 'endDate', type: 'uint40' },
      { name: 'status', type: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cUSD',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'premiumPool',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'authorizedAgent',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_PREMIUM',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_COVERAGE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PolicyRegistered',
    inputs: [
      { name: 'policyId', type: 'bytes32', indexed: true },
      { name: 'farmer', type: 'address', indexed: true },
      { name: 'coverageType', type: 'uint8', indexed: false },
      { name: 'coverageAmount', type: 'uint256', indexed: false },
      { name: 'endDate', type: 'uint40', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PolicyClaimed',
    inputs: [
      { name: 'policyId', type: 'bytes32', indexed: true },
      { name: 'farmer', type: 'address', indexed: true },
      { name: 'payout', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PolicyExpired',
    inputs: [{ name: 'policyId', type: 'bytes32', indexed: true }],
  },
  { type: 'error', name: 'Unauthorized', inputs: [] },
  { type: 'error', name: 'InvalidPremium', inputs: [] },
  { type: 'error', name: 'InvalidCoverage', inputs: [] },
  { type: 'error', name: 'InvalidDuration', inputs: [] },
  { type: 'error', name: 'PolicyNotActive', inputs: [] },
  { type: 'error', name: 'PolicyAlreadyExists', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
] as const;
